# Generated by Django 5.1.2 on 2024-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(),
        ),
    ]
