# Generated by Django 5.1.2 on 2024-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0006_alter_voter_apartment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
