# Generated by Django 5.1.2 on 2024-11-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0007_voter_voter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter_number',
        ),
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
