# Generated by Django 5.1.2 on 2024-11-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team1_image_url', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=50)),
                ('team2_image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
