# Generated by Django 5.1.2 on 2024-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='three_pointers_made_per_game',
        ),
        migrations.AddField(
            model_name='player',
            name='three_pointers_per_game',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
    ]
