# Generated by Django 5.1.2 on 2024-12-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_player_three_pointers_made_per_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamelog',
            name='opponent',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
    ]
