# Generated by Django 5.1.2 on 2024-12-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_playergamelog_opponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamelog',
            name='three_pointers_attempted',
        ),
        migrations.RemoveField(
            model_name='playergamelog',
            name='three_pointers_made',
        ),
        migrations.AddField(
            model_name='playergamelog',
            name='three_pointers',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
    ]
